// This is an autogenerated file from Firebase Studio.
import { initializeApp, getApps, getApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";

const firebaseConfig = null;

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig!) : getApp();
const db = getFirestore(app);

export { app, db };
