// This is an autogenerated file from Firebase Studio.
import { db } from '@/firebase';
import type { Category } from '@/lib/types';
import { collection, getDocs, addDoc, deleteDoc, doc, DocumentData, QueryDocumentSnapshot } from 'firebase/firestore';

const getCategoryCollection = () => collection(db, 'categories');

const fromFirestore = (snapshot: QueryDocumentSnapshot<DocumentData>): Category => {
    const data = snapshot.data();
    return {
        ...data,
        id: snapshot.id,
    } as Category;
}

export const getCategories = async (): Promise<Category[]> => {
    const snapshot = await getDocs(getCategoryCollection());
    return snapshot.docs.map(fromFirestore);
};

export const addCategory = async (category: Omit<Category, 'id'>) => {
    const docRef = await addDoc(getCategoryCollection(), category);
    return docRef.id;
};

export const deleteCategory = async (id: string) => {
    const categoryDoc = doc(db, 'categories', id);
    await deleteDoc(categoryDoc);
};
