// This is an autogenerated file from Firebase Studio.
import { db } from '@/lib/firebase';
import type { Order, OrderStatus } from '@/lib/types';
import { collection, getDocs, addDoc, updateDoc, doc, DocumentData, QueryDocumentSnapshot } from 'firebase/firestore';

const orderCollection = collection(db, 'orders');

const fromFirestore = (snapshot: QueryDocumentSnapshot<DocumentData>): Order => {
    const data = snapshot.data();
    return {
        ...data,
        id: snapshot.id,
        date: data.date.toDate().toISOString(),
    } as Order;
}

export const getOrders = async (): Promise<Order[]> => {
    const snapshot = await getDocs(orderCollection);
    return snapshot.docs.map(fromFirestore);
};

export const addOrder = async (order: Omit<Order, 'id' | 'date' | 'status'>) => {
    const newOrder = {
        ...order,
        date: new Date(),
        status: 'En attente',
    }
    const docRef = await addDoc(orderCollection, newOrder);
    return docRef.id;
};

export const updateOrderStatus = async (id: string, status: OrderStatus) => {
    const orderDoc = doc(db, 'orders', id);
    await updateDoc(orderDoc, { status });
};
