// This is an autogenerated file from Firebase Studio.
'use client';
import { db } from '@/firebase';
import type { Order, OrderStatus } from '@/lib/types';
import { collection, getDocs, addDoc, updateDoc, doc, DocumentData, QueryDocumentSnapshot, query, where, serverTimestamp } from 'firebase/firestore';

const getOrderCollection = () => collection(db, 'orders');

const fromFirestore = (snapshot: QueryDocumentSnapshot<DocumentData>): Order => {
    const data = snapshot.data();
    const date = data.date?.toDate ? data.date.toDate().toISOString() : new Date().toISOString();
    return {
        ...data,
        id: snapshot.id,
        date: date,
    } as Order;
}

export const getOrdersByUserId = async (userId: string): Promise<Order[]> => {
    const q = query(getOrderCollection(), where("userId", "==", userId));
    const snapshot = await getDocs(q);
    return snapshot.docs.map(fromFirestore);
};

export const getOrders = async (): Promise<Order[]> => {
    const snapshot = await getDocs(getOrderCollection());
    return snapshot.docs.map(fromFirestore);
};

export const addOrder = async (order: Omit<Order, 'id' | 'date' | 'status'>) => {
    const newOrder = {
        ...order,
        date: serverTimestamp(),
        status: 'En attente',
    }
    const docRef = await addDoc(getOrderCollection(), newOrder);
    return docRef?.id;
};

export const updateOrderStatus = async (id: string, status: OrderStatus) => {
    const orderDoc = doc(db, 'orders', id);
    await updateDoc(orderDoc, { status });
};
