// This is an autogenerated file from Firebase Studio.
import { db } from '@/lib/firebase';
import type { Shoe } from '@/lib/types';
import { collection, getDocs, addDoc, updateDoc, deleteDoc, doc, DocumentData, QueryDocumentSnapshot } from 'firebase/firestore';

const shoeCollection = collection(db, 'shoes');

const fromFirestore = (snapshot: QueryDocumentSnapshot<DocumentData>): Shoe => {
    const data = snapshot.data();
    return {
        ...data,
        id: snapshot.id,
    } as Shoe;
}

export const getProducts = async (): Promise<Shoe[]> => {
    const snapshot = await getDocs(shoeCollection);
    return snapshot.docs.map(fromFirestore);
};

export const addProduct = async (shoe: Omit<Shoe, 'id'>) => {
    const docRef = await addDoc(shoeCollection, shoe);
    return docRef.id;
};

export const updateProduct = async (id: string, shoe: Partial<Shoe>) => {
    const shoeDoc = doc(db, 'shoes', id);
    await updateDoc(shoeDoc, shoe);
};

export const deleteProduct = async (id: string) => {
    const shoeDoc = doc(db, 'shoes', id);
    await deleteDoc(shoeDoc);
};
