// This is an autogenerated file from Firebase Studio.
import { db } from '@/firebase';
import type { PromoCode } from '@/lib/types';
import { collection, getDocs, addDoc, updateDoc, deleteDoc, doc, where, query, limit, DocumentData, QueryDocumentSnapshot } from 'firebase/firestore';

const getPromoCodeCollection = () => collection(db, 'promoCodes');

const fromFirestore = (snapshot: QueryDocumentSnapshot<DocumentData>): PromoCode => {
    const data = snapshot.data();
    return {
        ...data,
        id: snapshot.id,
    } as PromoCode;
}

export const getPromoCodes = async (): Promise<PromoCode[]> => {
    const snapshot = await getDocs(getPromoCodeCollection());
    return snapshot.docs.map(fromFirestore);
};

export const getPromoCodeByCode = async (code: string): Promise<PromoCode | null> => {
    const q = query(getPromoCodeCollection(), where("code", "==", code.toUpperCase()), limit(1));
    const snapshot = await getDocs(q);
    if (snapshot.empty) {
        return null;
    }
    return fromFirestore(snapshot.docs[0]);
}

export const addPromoCode = async (promoCode: Omit<PromoCode, 'id'>) => {
    const docRef = await addDoc(getPromoCodeCollection(), promoCode);
    return docRef.id;
};

export const updatePromoCode = async (id: string, promoCode: Partial<Omit<PromoCode, 'id'>>) => {
    const promoCodeDoc = doc(db, 'promoCodes', id);
    await updateDoc(promoCodeDoc, promoCode);
};

export const deletePromoCode = async (id: string) => {
    const promoCodeDoc = doc(db, 'promoCodes', id);
    await deleteDoc(promoCodeDoc);
};
